/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author luis
 */
public class Asientos extends javax.swing.JFrame {

    /**
     * Creates new form Asientos
     */
    public Asientos() {
        initComponents();
        this.setSize(633, 430);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();
        jButton42 = new javax.swing.JButton();
        jButton43 = new javax.swing.JButton();
        jButton44 = new javax.swing.JButton();
        jButton45 = new javax.swing.JButton();
        jButton46 = new javax.swing.JButton();
        jButton47 = new javax.swing.JButton();
        jButton48 = new javax.swing.JButton();
        jButton49 = new javax.swing.JButton();
        jButton50 = new javax.swing.JButton();
        jButton51 = new javax.swing.JButton();
        jButton52 = new javax.swing.JButton();
        jButton53 = new javax.swing.JButton();
        jButton54 = new javax.swing.JButton();
        jButton55 = new javax.swing.JButton();
        jButton56 = new javax.swing.JButton();
        jButton57 = new javax.swing.JButton();
        jButton58 = new javax.swing.JButton();
        jButton59 = new javax.swing.JButton();
        jButton60 = new javax.swing.JButton();
        jButton61 = new javax.swing.JButton();
        jButton62 = new javax.swing.JButton();
        jButton63 = new javax.swing.JButton();
        jButton64 = new javax.swing.JButton();
        jButton65 = new javax.swing.JButton();
        jButton66 = new javax.swing.JButton();
        jButton67 = new javax.swing.JButton();
        jButton68 = new javax.swing.JButton();
        jButton69 = new javax.swing.JButton();
        jButton70 = new javax.swing.JButton();
        jButton71 = new javax.swing.JButton();
        jButton72 = new javax.swing.JButton();
        jButton73 = new javax.swing.JButton();
        jButton74 = new javax.swing.JButton();
        jButton75 = new javax.swing.JButton();
        jButton76 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton1.setText("Siguiente");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(513, 370, 90, 23);
        getContentPane().add(jButton2);
        jButton2.setBounds(520, 230, 30, 30);

        jButton3.setOpaque(false);
        getContentPane().add(jButton3);
        jButton3.setBounds(70, 80, 30, 30);
        getContentPane().add(jButton4);
        jButton4.setBounds(100, 80, 30, 30);
        getContentPane().add(jButton5);
        jButton5.setBounds(130, 80, 30, 30);
        getContentPane().add(jButton6);
        jButton6.setBounds(160, 80, 30, 30);
        getContentPane().add(jButton7);
        jButton7.setBounds(200, 80, 30, 30);
        getContentPane().add(jButton8);
        jButton8.setBounds(230, 80, 30, 30);
        getContentPane().add(jButton9);
        jButton9.setBounds(260, 80, 30, 30);
        getContentPane().add(jButton10);
        jButton10.setBounds(290, 80, 30, 30);
        getContentPane().add(jButton11);
        jButton11.setBounds(320, 80, 30, 30);
        getContentPane().add(jButton12);
        jButton12.setBounds(360, 80, 30, 30);
        getContentPane().add(jButton13);
        jButton13.setBounds(390, 80, 30, 30);
        getContentPane().add(jButton14);
        jButton14.setBounds(420, 80, 30, 30);
        getContentPane().add(jButton15);
        jButton15.setBounds(450, 80, 30, 30);
        getContentPane().add(jButton16);
        jButton16.setBounds(480, 80, 30, 30);
        getContentPane().add(jButton17);
        jButton17.setBounds(520, 80, 30, 30);
        getContentPane().add(jButton18);
        jButton18.setBounds(70, 120, 30, 30);
        getContentPane().add(jButton19);
        jButton19.setBounds(100, 120, 30, 30);
        getContentPane().add(jButton20);
        jButton20.setBounds(130, 120, 30, 30);
        getContentPane().add(jButton21);
        jButton21.setBounds(160, 120, 30, 30);
        getContentPane().add(jButton22);
        jButton22.setBounds(200, 120, 30, 30);
        getContentPane().add(jButton23);
        jButton23.setBounds(230, 120, 30, 30);
        getContentPane().add(jButton24);
        jButton24.setBounds(260, 120, 30, 30);
        getContentPane().add(jButton25);
        jButton25.setBounds(290, 120, 30, 30);
        getContentPane().add(jButton26);
        jButton26.setBounds(330, 120, 30, 30);
        getContentPane().add(jButton27);
        jButton27.setBounds(360, 120, 30, 30);
        getContentPane().add(jButton28);
        jButton28.setBounds(390, 120, 30, 30);
        getContentPane().add(jButton29);
        jButton29.setBounds(420, 120, 30, 30);
        getContentPane().add(jButton30);
        jButton30.setBounds(450, 120, 30, 30);
        getContentPane().add(jButton31);
        jButton31.setBounds(480, 120, 30, 30);
        getContentPane().add(jButton32);
        jButton32.setBounds(520, 120, 30, 30);
        getContentPane().add(jButton33);
        jButton33.setBounds(70, 160, 30, 30);
        getContentPane().add(jButton34);
        jButton34.setBounds(100, 160, 30, 30);
        getContentPane().add(jButton35);
        jButton35.setBounds(130, 160, 30, 30);
        getContentPane().add(jButton36);
        jButton36.setBounds(170, 160, 30, 30);
        getContentPane().add(jButton37);
        jButton37.setBounds(200, 160, 30, 30);
        getContentPane().add(jButton38);
        jButton38.setBounds(230, 160, 30, 30);
        getContentPane().add(jButton39);
        jButton39.setBounds(260, 160, 30, 30);
        getContentPane().add(jButton40);
        jButton40.setBounds(290, 160, 30, 30);
        getContentPane().add(jButton41);
        jButton41.setBounds(330, 160, 30, 30);
        getContentPane().add(jButton42);
        jButton42.setBounds(360, 160, 30, 30);
        getContentPane().add(jButton43);
        jButton43.setBounds(390, 160, 30, 30);
        getContentPane().add(jButton44);
        jButton44.setBounds(420, 160, 30, 30);
        getContentPane().add(jButton45);
        jButton45.setBounds(450, 160, 30, 30);
        getContentPane().add(jButton46);
        jButton46.setBounds(480, 160, 30, 30);
        getContentPane().add(jButton47);
        jButton47.setBounds(520, 160, 30, 30);
        getContentPane().add(jButton48);
        jButton48.setBounds(70, 190, 30, 30);
        getContentPane().add(jButton49);
        jButton49.setBounds(100, 190, 30, 30);
        getContentPane().add(jButton50);
        jButton50.setBounds(130, 190, 30, 30);
        getContentPane().add(jButton51);
        jButton51.setBounds(170, 190, 30, 30);
        getContentPane().add(jButton52);
        jButton52.setBounds(200, 190, 30, 30);
        getContentPane().add(jButton53);
        jButton53.setBounds(230, 190, 30, 30);

        jButton54.setBorderPainted(false);
        getContentPane().add(jButton54);
        jButton54.setBounds(260, 190, 30, 30);
        getContentPane().add(jButton55);
        jButton55.setBounds(290, 190, 30, 30);
        getContentPane().add(jButton56);
        jButton56.setBounds(390, 190, 30, 30);
        getContentPane().add(jButton57);
        jButton57.setBounds(420, 190, 30, 30);
        getContentPane().add(jButton58);
        jButton58.setBounds(450, 190, 30, 30);
        getContentPane().add(jButton59);
        jButton59.setBounds(480, 190, 30, 30);
        getContentPane().add(jButton60);
        jButton60.setBounds(520, 190, 30, 30);
        getContentPane().add(jButton61);
        jButton61.setBounds(70, 230, 30, 30);
        getContentPane().add(jButton62);
        jButton62.setBounds(100, 230, 30, 30);
        getContentPane().add(jButton63);
        jButton63.setBounds(330, 190, 30, 30);
        getContentPane().add(jButton64);
        jButton64.setBounds(360, 190, 30, 30);
        getContentPane().add(jButton65);
        jButton65.setBounds(200, 230, 30, 30);
        getContentPane().add(jButton66);
        jButton66.setBounds(230, 230, 30, 30);
        getContentPane().add(jButton67);
        jButton67.setBounds(260, 230, 30, 30);
        getContentPane().add(jButton68);
        jButton68.setBounds(290, 230, 30, 30);
        getContentPane().add(jButton69);
        jButton69.setBounds(330, 230, 30, 30);
        getContentPane().add(jButton70);
        jButton70.setBounds(360, 230, 30, 30);
        getContentPane().add(jButton71);
        jButton71.setBounds(390, 230, 30, 30);
        getContentPane().add(jButton72);
        jButton72.setBounds(420, 230, 30, 30);
        getContentPane().add(jButton73);
        jButton73.setBounds(450, 230, 30, 30);
        getContentPane().add(jButton74);
        jButton74.setBounds(480, 230, 30, 30);
        getContentPane().add(jButton75);
        jButton75.setBounds(130, 230, 30, 30);
        getContentPane().add(jButton76);
        jButton76.setBounds(170, 230, 30, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PANTALLA.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 70, 490, 290);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Selecciona la butaca");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(200, 20, 230, 29);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/redcurtain.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 630, 410);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        VentanaFactura ventanafactura= new VentanaFactura();
        this.setVisible(false);
        ventanafactura.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Asientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Asientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Asientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Asientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Asientos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton42;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton45;
    private javax.swing.JButton jButton46;
    private javax.swing.JButton jButton47;
    private javax.swing.JButton jButton48;
    private javax.swing.JButton jButton49;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton50;
    private javax.swing.JButton jButton51;
    private javax.swing.JButton jButton52;
    private javax.swing.JButton jButton53;
    private javax.swing.JButton jButton54;
    private javax.swing.JButton jButton55;
    private javax.swing.JButton jButton56;
    private javax.swing.JButton jButton57;
    private javax.swing.JButton jButton58;
    private javax.swing.JButton jButton59;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton60;
    private javax.swing.JButton jButton61;
    private javax.swing.JButton jButton62;
    private javax.swing.JButton jButton63;
    private javax.swing.JButton jButton64;
    private javax.swing.JButton jButton65;
    private javax.swing.JButton jButton66;
    private javax.swing.JButton jButton67;
    private javax.swing.JButton jButton68;
    private javax.swing.JButton jButton69;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton70;
    private javax.swing.JButton jButton71;
    private javax.swing.JButton jButton72;
    private javax.swing.JButton jButton73;
    private javax.swing.JButton jButton74;
    private javax.swing.JButton jButton75;
    private javax.swing.JButton jButton76;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
