
import java.io.IOException;
import java.net.ConnectException;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author luis
 */
public class Inicio extends javax.swing.JFrame {

    private Admin admin;

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        this.setSize(255, 180);
        this.setResizable(false);
        this.admin = new Admin();
        admin.agregarPelicula("Spider-Man", "", "156 Min", 2, "Peliculas/spider-man.png");
        admin.agregarPelicula("Planeta de los Simios", "", "166 Min", 2, "Peliculas/Dawn-Planet-of-the-Apes-Poster-Large-128x128.jpg");
        admin.agregarPelicula("Anabelle 2", "", "146 Min", 3, "Peliculas/ana.jpg");
        admin.agregarPelicula("Cars 3", "", "176 Min", 1, "Peliculas/cars-3.jpg");
        admin.agregarPelicula("Emoji", "", "136 Min", 1, "Peliculas/emoji.jpeg");
        admin.agregarPelicula("Mi vilano Favorito 3", "", "126 Min", 1, "Peliculas/mi.jpg");

        Sala2D sala2D = new Sala2D("Sala 2D");
        Sala3D sala3D = new Sala3D("Sala 3D");
        SalaVIP salavip = new SalaVIP("Sala VIP");

        admin.agregarSalaPelicula(sala2D, "Spider-Man");
        admin.agregarSalaPelicula(sala3D, "Spider-Man");
        admin.agregarSalaPelicula(salavip, "Spider-Man");

        admin.agregarSalaPelicula(sala2D, "Planeta de los Simios");
        admin.agregarSalaPelicula(sala3D, "Planeta de los Simios");
        admin.agregarSalaPelicula(salavip, "Planeta de los Simios");

        admin.agregarSalaPelicula(sala2D, "Anabelle 2");
        admin.agregarSalaPelicula(sala3D, "Anabelle 2");
        admin.agregarSalaPelicula(salavip, "Anabelle 2");

        admin.agregarSalaPelicula(sala2D, "Cars 3");
        admin.agregarSalaPelicula(sala3D, "Cars 3");

        admin.agregarSalaPelicula(sala2D, "Emoji");

        admin.agregarSalaPelicula(sala2D, "Mi vilano Favorito 3");
        admin.agregarSalaPelicula(sala3D, "Mi vilano Favorito 3");

    }

    private void Conectar() {

        String nombre = txtNombre.getText();
        int puerto = Integer.parseInt(txtPuerto.getText());

        Client cliente = new Client(nombre, puerto);
        admin = cliente.recibirAdmin();
        
        if(admin==null){
        JOptionPane.showMessageDialog(this, "Ocurrió un error");
        }else{
        VentanaPrincipal ventanaprincipal = new VentanaPrincipal(admin);
        this.setVisible(false);
        ventanaprincipal.setVisible(true);
        
        
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtPuerto = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(null);

        jLabel1.setText("Nombre:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 40, 50, 17);

        jLabel2.setText("Puerto:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 80, 50, 17);

        txtNombre.setText("localhost");
        getContentPane().add(txtNombre);
        txtNombre.setBounds(100, 30, 128, 30);

        txtPuerto.setText("4445");
        getContentPane().add(txtPuerto);
        txtPuerto.setBounds(100, 70, 128, 30);

        jButton1.setText("En red");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(60, 110, 90, 27);

        jLabel3.setText("Cinema 4000");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(90, 10, 70, 17);

        jButton2.setText("Conectar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(160, 110, 90, 27);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        Conectar();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        VentanaPrincipal ventanaprincipal = new VentanaPrincipal(admin);
        this.setVisible(false);
        ventanaprincipal.setVisible(true);

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPuerto;
    // End of variables declaration//GEN-END:variables
}
