
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author luis
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        Admin admin= new Admin();
        admin.agregarPelicula("Spider-Man", "", "156 Min", 2, "Peliculas/spiderman.jpg");
        Pelicula pelicula=admin.getPeliculas().get(0);
        //imagen1.setIcon(pelicula.getPhoto());
        imagen1.setIcon(new ImageIcon("../Peliculas/spiderman.jpg"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imagen1 = new javax.swing.JLabel();
        imagen3 = new javax.swing.JLabel();
        imagen5 = new javax.swing.JLabel();
        nombre1 = new javax.swing.JLabel();
        nombre3 = new javax.swing.JLabel();
        nombre5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        imagen1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Peliculas/Dawn-Planet-of-the-Apes-Poster-Large-128x128.jpg"))); // NOI18N
        getContentPane().add(imagen1);
        imagen1.setBounds(50, 40, 130, 130);

        imagen3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Peliculas/cars-3-film.jpg"))); // NOI18N
        getContentPane().add(imagen3);
        imagen3.setBounds(300, 30, 130, 128);

        imagen5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Peliculas/despicable-me-3-war-planet-apes-14.jpeg"))); // NOI18N
        getContentPane().add(imagen5);
        imagen5.setBounds(550, 40, 128, 128);

        nombre1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Peliculas/emoji-movie-spiderman-homecoming-99.jpeg"))); // NOI18N
        nombre1.setText("jLabel8");
        getContentPane().add(nombre1);
        nombre1.setBounds(50, 260, 130, 130);

        nombre3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Peliculas/spider-man_homecoming_recensione-128x128.png"))); // NOI18N
        nombre3.setText("jLabel10");
        getContentPane().add(nombre3);
        nombre3.setBounds(310, 260, 130, 130);

        nombre5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Peliculas/figure-016311.jpg"))); // NOI18N
        nombre5.setText("jLabel12");
        getContentPane().add(nombre5);
        nombre5.setBounds(550, 260, 130, 128);

        jButton1.setText("Planeta de los Simios");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(50, 180, 140, 23);

        jButton2.setText("Cars 3");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(310, 180, 120, 23);

        jButton3.setText("Mi villano favorito 3");
        getContentPane().add(jButton3);
        jButton3.setBounds(550, 180, 130, 23);

        jButton4.setText("Emoji");
        getContentPane().add(jButton4);
        jButton4.setBounds(50, 400, 140, 23);

        jButton5.setText("Spiderman Home Coming");
        getContentPane().add(jButton5);
        jButton5.setBounds(300, 400, 150, 23);

        jButton6.setText("Annabelle 2");
        getContentPane().add(jButton6);
        jButton6.setBounds(550, 400, 130, 23);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sala4.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 730, 470);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imagen1;
    private javax.swing.JLabel imagen3;
    private javax.swing.JLabel imagen5;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel nombre1;
    private javax.swing.JLabel nombre3;
    private javax.swing.JLabel nombre5;
    // End of variables declaration//GEN-END:variables
}
