
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author luis
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    private Admin admin;

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal(Admin admin) {
        initComponents();
        this.admin = admin;
        
        
        this.setSize(732, 468);
        this.setResizable(false);
        //JOptionPane.showMessageDialog(this, pelicula.getNombre());
        generarPeliculas();
    }

    public void generarPeliculas() {
        List listapeliculas = admin.getPeliculas();
        int tamano = listapeliculas.size();
        for (int i = 0; i < tamano; i++) {
            
            Pelicula peli= (Pelicula) listapeliculas.get(i);
            switch (i){
                case 0:
                    JButton button =   pelicula1;
                    button.setText(peli.getNombre());
                    JLabel label = imagen1;
                    label.setIcon(peli.getPhoto());
                    break;
                case 1:
                    JButton button2 =   pelicula2;
                    button2.setText(peli.getNombre());
                    JLabel label2 = imagen2;
                    label2.setIcon(peli.getPhoto());
                    break;
                case 2:
                    JButton button3 =   pelicula3;
                    button3.setText(peli.getNombre());
                    JLabel label3 = imagen3;
                    label3.setIcon(peli.getPhoto());
                    break;
                case 3:
                    JButton button4 =   pelicula4;
                    button4.setText(peli.getNombre());
                    JLabel label4 = imagen4;
                    label4.setIcon(peli.getPhoto()); 
                    break;
                case 4:
                    JButton button5 =   pelicula5;
                    button5.setText(peli.getNombre());
                    JLabel label5 = imagen5;
                    label5.setIcon(peli.getPhoto());
                    break;
                case 5:
                    JButton button6 =   pelicula6;
                    button6.setText(peli.getNombre());
                    JLabel label6 = imagen6;
                    label6.setIcon(peli.getPhoto());
                    break;
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imagen1 = new javax.swing.JLabel();
        imagen2 = new javax.swing.JLabel();
        imagen3 = new javax.swing.JLabel();
        imagen4 = new javax.swing.JLabel();
        imagen5 = new javax.swing.JLabel();
        imagen6 = new javax.swing.JLabel();
        pelicula1 = new javax.swing.JButton();
        pelicula2 = new javax.swing.JButton();
        pelicula3 = new javax.swing.JButton();
        pelicula4 = new javax.swing.JButton();
        pelicula5 = new javax.swing.JButton();
        pelicula6 = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(imagen1);
        imagen1.setBounds(40, 30, 160, 140);
        getContentPane().add(imagen2);
        imagen2.setBounds(310, 30, 130, 140);

        imagen3.setBackground(new java.awt.Color(7, 2, 2));
        getContentPane().add(imagen3);
        imagen3.setBounds(540, 30, 130, 140);
        getContentPane().add(imagen4);
        imagen4.setBounds(50, 240, 140, 140);
        getContentPane().add(imagen5);
        imagen5.setBounds(290, 230, 160, 140);
        getContentPane().add(imagen6);
        imagen6.setBounds(540, 240, 150, 140);

        pelicula1.setText("Pelicula1");
        pelicula1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pelicula1ActionPerformed(evt);
            }
        });
        getContentPane().add(pelicula1);
        pelicula1.setBounds(40, 180, 160, 27);

        pelicula2.setText("Pelicula2");
        pelicula2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pelicula2ActionPerformed(evt);
            }
        });
        getContentPane().add(pelicula2);
        pelicula2.setBounds(290, 180, 160, 27);

        pelicula3.setText("Pelicula3");
        pelicula3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pelicula3ActionPerformed(evt);
            }
        });
        getContentPane().add(pelicula3);
        pelicula3.setBounds(540, 180, 140, 27);

        pelicula4.setText("Pelicula4");
        pelicula4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pelicula4ActionPerformed(evt);
            }
        });
        getContentPane().add(pelicula4);
        pelicula4.setBounds(40, 400, 170, 27);

        pelicula5.setText("Pelicula5");
        pelicula5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pelicula5ActionPerformed(evt);
            }
        });
        getContentPane().add(pelicula5);
        pelicula5.setBounds(280, 400, 190, 27);

        pelicula6.setText("Pelicula6");
        pelicula6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pelicula6ActionPerformed(evt);
            }
        });
        getContentPane().add(pelicula6);
        pelicula6.setBounds(530, 400, 160, 27);

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sala4.jpg"))); // NOI18N
        getContentPane().add(fondo);
        fondo.setBounds(-10, -120, 850, 730);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pelicula2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pelicula2ActionPerformed
        HorarioyTiquetes horarioytiquetes = new HorarioyTiquetes();
        this.setVisible(false);
        horarioytiquetes.setVisible(true);
    }//GEN-LAST:event_pelicula2ActionPerformed

    private void pelicula1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pelicula1ActionPerformed
        HorarioyTiquetes horarioytiquetes = new HorarioyTiquetes();
        this.setVisible(false);
        horarioytiquetes.setVisible(true);
    }//GEN-LAST:event_pelicula1ActionPerformed

    private void pelicula3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pelicula3ActionPerformed
        HorarioyTiquetes horarioytiquetes = new HorarioyTiquetes();
        this.setVisible(false);
        horarioytiquetes.setVisible(true);
    }//GEN-LAST:event_pelicula3ActionPerformed

    private void pelicula4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pelicula4ActionPerformed
        HorarioyTiquetes horarioytiquetes = new HorarioyTiquetes();
        this.setVisible(false);
        horarioytiquetes.setVisible(true);
    }//GEN-LAST:event_pelicula4ActionPerformed

    private void pelicula5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pelicula5ActionPerformed
        HorarioyTiquetes horarioytiquetes = new HorarioyTiquetes();
        this.setVisible(false);
        horarioytiquetes.setVisible(true);
    }//GEN-LAST:event_pelicula5ActionPerformed

    private void pelicula6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pelicula6ActionPerformed
        HorarioyTiquetes horarioytiquetes = new HorarioyTiquetes();
        this.setVisible(false);
        horarioytiquetes.setVisible(true);
    }//GEN-LAST:event_pelicula6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel imagen1;
    private javax.swing.JLabel imagen2;
    private javax.swing.JLabel imagen3;
    private javax.swing.JLabel imagen4;
    private javax.swing.JLabel imagen5;
    private javax.swing.JLabel imagen6;
    private javax.swing.JButton pelicula1;
    private javax.swing.JButton pelicula2;
    private javax.swing.JButton pelicula3;
    private javax.swing.JButton pelicula4;
    private javax.swing.JButton pelicula5;
    private javax.swing.JButton pelicula6;
    // End of variables declaration//GEN-END:variables
}
